config/routes.rb
Rails.application.routes.draw do
  resources :students

  root to: 'students#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :students

  validates :name, presence: true
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :group, optional: true

  validates  :name,
             :surname,
             :birthdate,
             :email,
             presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.order(:surname, :name)
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new

    respond_to do |format|
      format.js
      format.html
    end
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = RegisterStudent.new(student_params, request.remote_ip).call

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render json: { status: :ok, student: @student } }
        format.js   { render :create }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
        format.js   { render :new }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:name, :surname, :group, :birthdate, :email, :inet, :registered_at, :avg_rating)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper

  def format_russian_date(date)
    date.strftime('%d/%m/%Y')
  end

  def format_russian_datetime(datetime)
    datetime.strftime('%d/%m/%Y %I:%M')
  end

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Registry
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    = yield

app/views/students/_form.html.haml
= simple_form_for(@student, validate: true, remote: true) do |form|
  = form.input :name, label: 'Name'
  = form.input :surname, label: 'Surname'
  = form.input :birthdate, as: :date_picker, start_year: Date.today.year - 90,
                    label: 'Birthdate', id: :student_birthdate, placeholder: 'dd/mm/yyyy'
  = form.input :email, label: 'Email'
  = form.submit

app/views/students/_modal.html.haml
#student-modal.modal.fade{:role => "dialog"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"data-dismiss" => "modal", :type => "button"} ×
        %h4.modal-title Student form
      .modal-body
        = render 'form'
        .form-errors
      .modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Close

app/views/students/_row.html.haml
%tr
  %td= student.surname
  %td= student.name
  %td= student.group
  %td= format_russian_date(student.birthdate)
  %td= student.email
  %td= format_russian_datetime(student.registered_at)
  %td= student.avg_rating
  %td= link_to 'Show', student
  %td= link_to 'Edit', edit_student_path(student)
  %td= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' }

app/views/students/create.js.erb
$('.students-tbody').append('<%= escape_javascript(render "row", student: @student) %>');
$('.students-count').html('(' + (parseInt($('.students-count').html().match(/\d+/)[0]) + 1) + ')');
$("#student-modal").modal('hide');
$('.modal-backdrop').remove();

app/views/students/edit.html.haml
%h1 Editing Student
= render 'form', student: @student
= link_to 'Show', @student
|
= link_to 'Back', students_path

app/views/students/index.html.haml
%p#notice= notice
%h1
  Students
  %span.students-count (#{@students.size})
%table.table.table-striped
  %thead
    %tr
      %th Surname
      %th Name
      %th Group
      %th Birthdate
      %th Email
      %th Registered at
      %th Avg rating
      %th{:colspan => "3"}
  %tbody.students-tbody
    = render partial: "row", collection: @students, as: :student
%br/

= link_to "New", new_student_path, remote: true, class: "btn btn-success new-student-btn"

#new_student_dialog_placeholder

app/views/students/new.html.haml
%h1 New Student
= render 'form', student: @student
= link_to 'Back', students_path

app/views/students/new.js.erb
$("#new_student_dialog_placeholder").html('<%= j render("modal") %>');
$("#student-modal").modal();
$('.datetimepicker').datetimepicker();

app/views/students/show.html.haml
%p#notice= notice
%p
  %strong Name:
  = @student.name
%p
  %strong Surname:
  = @student.surname
%p
  %strong Group:
  = @student&.group
%p
  %strong Birthdate:
  = @student.birthdate
%p
  %strong Email:
  = @student.email
%p
  %strong Avg rating:
  = @student.avg_rating
= link_to 'Edit', edit_student_path(@student)
|
= link_to 'Back', students_path